# Generated by Django 3.1 on 2021-04-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceimage',
            old_name='image',
            new_name='images',
        ),
    ]
