# Generated by Django 3.1 on 2021-04-04 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210404_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='serviceimage',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='service.service'),
        ),
    ]
